name: Build iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build app
        run: |
          xcodebuild -project "WorshipKeys Pads.xcodeproj" -scheme WorshipKeys -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' build

